language: python
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update -n base conda --yes
install:
  - conda create -n prysmci --yes python=3.7
  - source activate prysmci
  - >-
      conda install --yes
      numpy>=1.15
      scipy>=1.2
      matplotlib>=3.0
      imageio
      pandas
      h5py
      pytest=4.2.1
      pytest-cov=2.6.1
      coveralls=1.5.1
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give the virtual display time to boot up
script:
  - pytest --cov=prysm tests/
notifications:
  email: false
after_success:
  - coveralls
